# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'AInsigne' do
    pod 'Firebase', '>= 2.5.1'

end

target 'AInsigneTests' do

end

target 'AInsigneUITests' do

end

